### ISSUE TITLE
Layouts doesn't count dock

### ISSUE THREAD

**Issue by Antonio-Laguna** [jgallen23/layouts#1]
Hi there Greg,

It seems that Layouts isn't counting the height/width occupied by the dock. I've been watching the code and it seems that it's absolute positioned (in bottom-left and bottom right) in the middle of the screen but it shouldnt as it falls behind the dock.

I wasn't able to fix it but here you may find some interesting notes about it:

https://discussions.apple.com/thread/3553498?start=0&tstart=0

**Comment by jgallen23** [comment]
k, I'll look into this.

**Comment by jgallen23** [comment]
fixed in 2.1.0
